worker_processes auto;
events {
    worker_connections 1024;
}
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 50m;
    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
    upstream flask {
        server web:5000;
    }
    server {
        listen 80;
        server_name atmosfera-piter.ru www.atmosfera-piter.ru;
	location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
        location / {
            return 301 https://$host$request_uri;
        }
    }
    server {
        listen 443 ssl;
        server_name atmosfera-piter.ru www.atmosfera-piter.ru;
        ssl_certificate /etc/letsencrypt/live/atmosfera-piter.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/atmosfera-piter.ru/privkey.pem;
        location /static/ {
            alias /app/static/;
            expires 30d;
        }
        location / {
            proxy_pass http://flask;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
            proxy_read_timeout 120s;
        }
    }
}
